### ISSUE TITLE
[BS 0.1.5] Mode button doesn't seem to work anymore

### ISSUE THREAD

**Issue by Desempregago** [Natanaelel/BankStorage#1]
https://github.com/Natanaelel/BankStorage/assets/14002834/3161d1fc-0ea7-4abf-bd36-63e675433040

**Comment by Natanaelel** [comment]
does it work after rejoining?

**Comment by Natanaelel** [comment]
Fixed!
https://modrinth.com/mod/bank-storage/version/0.1.6
