### ISSUE TITLE
Get this crash on occasion

### ISSUE THREAD

**Issue by Daihok41** [Natanaelel/BankStorage#10]
**Describe the bug**

Get Crash on occasion when trying to place a block with build mode

**To Reproduce**

Hard to reproduce only happens sometimes

**Logs**
If applicable, add logs found in `minecraft-instance/logs/latest.log` and `minecraft-instance/crash-reports/<crashlog>.txt`

https://pastebin.com/sHcVZvfB

**Comment by Natanaelel** [comment]
You are using java 18. Try using 17.

**Comment by Natanaelel** [comment]
fixed in 1.0.0
https://modrinth.com/mod/bank-storage/version/1.0.0
