### ISSUE TITLE
build mode crash

### ISSUE THREAD

**Issue by lael-i** [Natanaelel/BankStorage#12]
**Describe the bug**
the game crashes to desktop while trying to place a block using the bank in build mode while sneaking.

**To Reproduce**
in trying, i've only had and been able to reproduce the crash in the nether. i've not tried any other dimensions. 
1. spawn in any bank, fill with any number of blocks
2. set bank to build mode
3. sneak-walk backwards and hold down the place block button to build a bridge over air
4. if needed, jitter view a little to simulate missing - the crash occurs on switching to random build mode and immediately placing a block

**Logs**
reproduced in an instance with only this mod: https://pastebin.com/YTngx2Sg

**Comment by Natanaelel** [comment]
This is known. Fixed in next update releasing soon. This can temporarily be solved by reconnecting to the world/server every time you switch dimensions.

**Comment by unilock** [comment]
@Natanaelel  
A new instance of `PlayerEntity` is created every time a player dies (and apparently changes dimensions?), correct? In which case, the "syncedRandom" field would return to `null` every time that happens, not just when the player first joins the server. Maybe a listener on `ServerPlayerEvents.COPY_FROM` would be enough?

Relevant code:  
https://github.com/Natanaelel/BankStorage/blob/99a2f1f2b8ac0f30f6c405d99d951a5e73aeb055/src/main/java/net/natte/bankstorage/BankStorage.java#L82-L89

**Comment by Natanaelel** [comment]
this is already fixed/closed.

**Comment by Natanaelel** [comment]
My bad. fix incoming
