### ISSUE TITLE
Bank storages can be used to duplicate items

### ISSUE THREAD

**Issue by Gkosgithubuser** [Natanaelel/BankStorage#14]
**Describe the bug**
Placing multiple bundles in a bank storage and right clicking places the item inside all of the stacked bundles

**To Reproduce**
Place two or more bundles into a bank storage
Right click an item while hovering over the bundle stack
Take the bundles out of the dank storage and right click them
Each bundle will contain a copy of the items put in

**Expected behavior**
The bank storage will not duplicate items placed inside and will instead put bundles with different contents in separate stacks/wont change inventories of other bundles

**Additional context**
Discovered to be working on the AOF6/7 modpack, haven't confirmed if it works on other versions

**Comment by Natanaelel** [comment]
Please make sure you are using bank storage and not dank. Dank has known duping issues. Bank storage is only used in aof 7.

**Comment by Gkosgithubuser** [comment]
I personally have only experienced the dupe with bank storage on aof7 but heard there was something similar on the previous version of the mod pack and assumed it was the same mod. So yes, it is bank storage and not dank storage with the duping issue

**Comment by Natanaelel** [comment]
Thanks. Yes I can replicate it in aof7 (1.1.0 as I had it downloaded).
Funnily enough:
https://github.com/Natanaelel/BankStorage/blob/main/src/main/java/net/natte/bankstorage/screen/BankScreenHandler.java#L570

**Comment by Natanaelel** [comment]
found the issue: this line was commented for some reason(??)
https://github.com/Natanaelel/BankStorage/blob/d2570c7dbc5683bdade1ec83cb640091a567178f/src/main/java/net/natte/bankstorage/screen/BankScreenHandler.java#L576
Will fix in next version (soon)

**Comment by Gkosgithubuser** [comment]
Thanks for fixing it so quick

**Comment by Natanaelel** [comment]
fixed in 1.0.0
https://modrinth.com/mod/bank-storage/version/1.0.0
