### ISSUE TITLE
the game crashed when I placed the bank in the docking station under the chute from the create mod

### ISSUE THREAD

**Issue by NNON0STOP** [Natanaelel/BankStorage#15]
Describe the bug
The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.method_3847(net.minecraft.class_5321)" because "server" is null

To Reproduce
1. place the dock under chute from create mod
2. Click on dock with bank
3. the game will freeze
4. game crash

Expected behavior
my world launch

Logs
[latest.log](https://github.com/Natanaelel/BankStorage/files/14653901/latest.log)

**Comment by Natanaelel** [comment]
Thank you for your report. Fixed in v1.0.1.
