### ISSUE TITLE
Right clicking to open bank in inventory while holding a block in the offhand places the block and opens the inventory

### ISSUE THREAD

**Issue by trunksbomb** [Natanaelel/BankStorage#16]
**Describe the bug**
Right clicking to open bank in inventory while holding a block in the offhand places the block and opens the inventory. I would expect right clicking the bank to open it would consume the right click event and not let it propagate to being able to place the block. Naturally this only occurs if you would otherwise be able to place the block in your offhand, such as looking at the ground in front of you or a wall.

**To Reproduce**
1. Put bank in your hotbar and a placeable block/item in your offhand
2. Be in a position where you could place the block in your offhand under normal conditions
3. Right click with the bank in your main hand to open it
4. Behold - you've opened the bank and placed a block

**Expected behavior**
Open bank, don't place block.

**Screenshots**
Nah

**Logs**
Nope

**Additional context**
Nuh uh

**Comment by Natanaelel** [comment]
Fixed in version 1.1.0
https://modrinth.com/mod/bank-storage/version/1.1.0
