### ISSUE TITLE
[Suggestion] Add keybind to open first bank found in inventory

### ISSUE THREAD

**Issue by trunksbomb** [Natanaelel/BankStorage#17]
This is a feature in the mod "Packed Up", another backpack mod. When you press your chosen keybind, it opens the first backpack (from Packed Up) it finds in your inventory, regardless of position. The backpack does not need to be worn (with the Curios API) nor on your hotbar.

This would be a neat function to add to this mod, if you're so inclined.

**Comment by Natanaelel** [comment]
great suggestion! will add.
