### ISSUE TITLE
"THIS WAS NOT SUPPOSED TO HAPPEN!" error message when opening Bank

### ISSUE THREAD

**Issue by trunksbomb** [Natanaelel/BankStorage#18]
**Describe the bug**
I'm not sure what the bug is, but you've coded the mod to shout at me when something breaks.

```
[23:31:44] [Render thread/INFO]: [CHAT] §c§lTHIS WAS NOT SUPPOSED TO HAPPEN!
§rPlease make a bug report
§rdescribing what caused this message to appear.
§rhttps://github.com/Natanaelel/BankStorage/issues
§rMath.Random PlayerEntity.bankstorage$getSyncedRandom() returned null
If this error persists, try rejoining the server/world.
```

**To Reproduce**
I'm not sure, but here's what I did recently:

1. Flew to the Stronghold and went to the End (already defeated the Dragon)
2. When I got there realized I was out of food so I came back through the portal
3. Got food, repeat step 1.
4. Mined about 2k obsidian out of one of the towers, which got picked up in on of my banks.
5. Went back through the portal
6. Opened my bank by looking at the floor at a normal construction block. Got the error message.
7. Shift-clicked obsidian out then deposited in ME and repeated a few times, getting the error message immediately upon opening the bank each time.

Other notes:
1. I have 3 banks in my inventory
2. The issue happens with each bank right now
3. The issue only happens when I look at a block and open it. If I open the bank in the air, it does not happen.
4. After disconnecting from the server and reconnecting, the issue is not happening anymore. I play on a locally hosted server.

**Expected behavior**
No big chat message!

**Screenshots**

![image](https://github.com/Natanaelel/BankStorage/assets/1904331/ea2a71fa-1d78-4758-afad-caa60e4289c9)
![image](https://github.com/Natanaelel/BankStorage/assets/1904331/8a79250e-5be1-4651-b209-7ea4ef584f3c)

**Logs**
If applicable, add logs found in `minecraft-instance/logs/latest.log` and `minecraft-instance/crash-reports/<crashlog>.txt`

**Additional context**

**Comment by Natanaelel** [comment]
Update to 1.0.2
