### ISSUE TITLE
Client side crash when hovering over an item >99 stack size

### ISSUE THREAD

**Issue by NotAModder** [Natanaelel/BankStorage#21]
**Mod version**
BankStorage 1.3.1

**Describe the bug**
Honestly not sure if this inherent to the mod but I'm coming across the issue while in the bank screen. Hovering over any stack with a stack size greater than 99 crashes the game. I just created an iron bank, hovering over a stack of 106 redstone. Game crashed. Repeated the process until I realized it was telling me it should be {1;99}. Item tag doesn't even show, just crashes

**To Reproduce**
1. Go to bank storage than can hold max size greater than 99
2. Hover over
3. Crash

Obviously there shouldn't be an issue when doing so as I've used mods in the past such as simple backpacks where stack sizes were increased. Somewhere in the code? I'm sure there is an exception made but I have no idea lol.

[crash-2024-06-21_00.35.36-client.txt](https://github.com/user-attachments/files/15922789/crash-2024-06-21_00.35.36-client.txt)
[debug.log](https://github.com/user-attachments/files/15922790/debug.log)

Just want to know if this is an issue with the mod or perhaps other mods that are conflicting with it. 

Sidenote: I removed expanded storage just to see if it was messing with anything and I was, for a moment, able to see the tag when hovering over the stack but the game still crashed

**Comment by Natanaelel** [comment]
I see something about harmonised/pmmo which is causing the issue. I almost guarantee you will crash with any other mod which has stacks > 99. Can you confirm?

**Comment by Natanaelel** [comment]
Is this a modpack I can download?

**Comment by JTK222** [comment]
Stack sizes over 99 are not intended in Minecraft, it has potential to break tons of stuff. (prior to 1.21 even 64)
If you need larger stack size, simulate them (save the stack size separately to the item stack, and display your own)
That's what basically every mod with those types of inventories does.

**Comment by Natanaelel** [comment]
> Stack sizes over 99 are not intended in Minecraft, it has potential to break tons of stuff. (prior to 1.21 even 64) If you need larger stack size, simulate them (save the stack size separately from the item stack, and display your own) That's what basically every mod with those types of inventories does.
Do you have an example?

**Comment by NotAModder** [comment]
Hi Natan. I can upload a zip of the modpack used with curseforge. Running NeoForge 21.0.21. Responses may be sparse today but I'll provide what I can! I'm sure it's not strictly due to your mod but I don't think I have a mod with any other stack size limits above 99.

**Comment by NotAModder** [comment]
I'm unable to send the zip. its 56mb

**Comment by Natanaelel** [comment]
Incompatible for now. Other mod can fix this easily.
