### ISSUE TITLE
Lockable slots

### ISSUE THREAD

**Issue by zax71** [Natanaelel/BankStorage#22]
**Is your feature request related to a problem? Please describe.**
I am attempting to use banks instead of MI barrels and it is hard to allow them to back up when all the slots can be used.

**Describe the solution you'd like**
Something like MI's slot locking so that we can lock the bank's slots to be empty or a specific item.

**Describe alternatives you've considered**
Using AE2 could work as the bank is in a dock but that requires lots of extra infrastructure that I do not want to put in for each bank

**Additional context**
The copper plates are depended on by the curved plates and thus get used up. When the curved plates are full, then they will go to another slot instead of stopping filling up at 256. I am using dirt as filler slots here so that partially solves the issue but still leaves that if we use all the copper plates then the setup could be messed up.
![image](https://github.com/Natanaelel/BankStorage/assets/67716263/686b2f56-6511-4a52-9b15-69733f43924a)

**Comment by Natanaelel** [comment]
Good news: this is already a feature! Hold alt and click the slots to lock. Check the keybinds!

**Comment by zax71** [comment]
Ah, thanks!
