### ISSUE TITLE
Reduced slot max  quantity

### ISSUE THREAD

**Issue by zax71** [Natanaelel/BankStorage#23]
**Is your feature request related to a problem? Please describe.**
I have to use bank ones instead of max levelled ones so that the slots can be filled and back up in the case of replacing MI barrels with docked banks

**Describe the solution you'd like**
Scrolling on the slots (like MI) should be able to decrease the max quantity. Seeing that the slot sizes go so big here, it might be good to use `shift` and `control` to increase the size changed per scroll click.

**Describe alternatives you've considered**
I could use smaller sized banks, but these have fewer slots, so the storage cannot be as compact

**Comment by Natanaelel** [comment]
Not planned. There are several other solutions: MI configurable chest, larger banks.
