### ISSUE TITLE
(NeoForge) Banks excluding the first one have no recipes displayed in JEI

### ISSUE THREAD

**Issue by Inonedn** [Natanaelel/BankStorage#25]
**Mod version**
1.3.7+1.21

**Describe the bug**
When its recipe is clicked on in JEI, its recipe is not displayed properly

**To Reproduce**
1. Install JEI
2. Click on the other banks
3. See error

**Expected behavior**
The recipe for said bank is shown

**Comment by Natanaelel** [comment]
JEI is not supported. I recommend EMI
