### ISSUE TITLE
Hoppers don't work to tranfer items into a docked bank

### ISSUE THREAD

**Issue by spaghettilmfao** [Natanaelel/BankStorage#26]
v1.2.1 in Minecraft 1.20.6

Using a hopper to tranfer items into a bank doesn't seem to work, is this intentional or a not yet implemented feature?

**Comment by Natanaelel** [comment]
Make sure you set the insert mode to allow items

**Comment by Natanaelel** [comment]
Reopen if you made sure it still doesn't work after adjusting insert mode.
