### ISSUE TITLE
Feature Request: Mod Settings

### ISSUE THREAD

**Issue by penturt** [Natanaelel/BankStorage#29]
Loving the mod, and so is my server. i have always been a huge fan of Dank Storage, but over the last few MC versions its been buggy and only getting worse. So I'm happy to have found this mod, it's everything i loved about Dank storage but without the glitches and also based on some stats a lot less intensive on the server.

If possible i have 2 recommendations, and maybe it could be part of a config file or in-game option. 

-> if it were possible to have an option to disable the "random build mode", or be able to assign it a different key, would just save a few extra clicks if its a mode you really don't use and also i have found myself in the wrong mode a few times.

-> Have options to either remove the "previous" and "next" items the shown in the preview while in build mode, or maybe shrink them in display size.

Nonetheless, even without this recommendations, the mod is great, i was considering "pocket storage" but didn't want to lose the some of the features i enjoy from "Dank Storage", I'm very happy i found this mod, i hope it picks up steam and gets included in more mod packs because its worth it.

**Comment by Natanaelel** [comment]
Both good suggestions! I'll look into this.

**Comment by penturt** [comment]
Nice, much appreciated

**Comment by Natanaelel** [comment]
I have implemented the first suggestion in 1.4.2+1.21. Backport to fabric 1.20.1 will come in a couple days.
I don't think the second suggestion makes sense for me to implement a whole config for. You can always edit the texture in a resource pack.

**Comment by penturt** [comment]
nice, thank you
