### ISSUE TITLE
Suggestion: Lock slots

### ISSUE THREAD

**Issue by Jaesaces** [Natanaelel/BankStorage#3]
### My Suggestion:
My suggestion is to allow the use of a keybind to "lock" a slot in the bank to only allow a particular item (or keep it empty).

### Example:

If the key combo for it is Shift-click:

If I shift click a slot that contains cobblestone, then that slot will only allow cobblestone there.  Even if you take the cobblestone out, no other items can go in that slot.

If I shift click an empty bank slot, then that slot will not fill with any items.

If I shift click a slot that is already locked, it will clear the lock, allowing any item to go into it again.

### Why?

This will allow the player to ensure that there is always space for a particular item.  Especially when docked and used to store byproducts (such as the sticks, logs, and other byproducts of cutting down trees) it will ensure that no one resource will block the others from being added when items are constantly being added/removed.

**Comment by Natanaelel** [comment]
Great idea, and great description. Will do.

**Comment by Natanaelel** [comment]
Added in 0.2.0
https://modrinth.com/mod/bank-storage/version/0.2.0
