### ISSUE TITLE
Random palette selector

### ISSUE THREAD

**Issue by HeavyDeception** [Natanaelel/BankStorage#30]
**Is your feature request related to a problem? Please describe.**
I love this mod but don't use the random build feature because it uses every single block in the bank.

**Describe the solution you'd like**
Have a way to select a few blocks and when you switch to random build mod it will use the "Palette" you have chosen. (would be nice if you could change the % of a block too so it would place that one more than the others kind of like how you would have with a Trowel from Quark by having a block take up 2 slots on your hot bar.).

**Describe alternatives you've considered**
You could build another bank but this is also a problem as you would have to remove blocks from your current bank and it just makes more of a hassle than anything.

**Comment by Natanaelel** [comment]
I won't add a palette feature as I think it:
1. Adds clutter for minimal benefit
2. It's already possible to mimic this behaviour by just using a 2nd bank.
If you fill multiple slots with the same item it will be picked more often.
