### ISSUE TITLE
Game/Server crash when placing a vanilla Hopper below a Bank Dock with a Bank Link inside

### ISSUE THREAD

**Issue by szernex** [Natanaelel/BankStorage#31]
**Mod version**
1.2.2

**Describe the bug**
The game/server crashes when you place a vanilla Hopper below a Bank Dock which has a Bank Link inside of it.

**To Reproduce**
Place Bank Dock
Place Bank Link inside
Place vanilla Hopper underneath

**Logs**
[crash-2024-10-28_00.38.33-server.txt](https://github.com/user-attachments/files/17535776/crash-2024-10-28_00.38.33-server.txt)

**Comment by Natanaelel** [comment]
Did you craft the bank link? It seems like you gave yourself a link without required nbt.

**Comment by szernex** [comment]
I didn't, I gave it to myself via creative, mainly because it was unclear to me how to use the Bank Link 😅
