### ISSUE TITLE
link not showing in JEI

### ISSUE THREAD

**Issue by DiggityMan420** [Natanaelel/BankStorage#33]
**Mod version**
Which version of the mod that was used.
[Bank Storage 1.4.2+1.21](https://www.curseforge.com/minecraft/mc-mods/bank-storage/files/5798040)
**Describe the bug**
jei doesn't show how to make bank link but you can manually place items and make it
 see Images
**To Reproduce**
1. log in
2. open jei search @bank
3. click bank link
4. doesnt show up on Use("u") or Recipe("r")
5. manually place items in crafting tank to make link

**Expected behavior**
link able to be seen in jei i guess
**Screenshots**
![Screenshot_15](https://github.com/user-attachments/assets/9b3ea27d-4eed-4728-aa54-1f14fc63d09b)
![Screenshot_16](https://github.com/user-attachments/assets/f00c9add-6c69-4d73-aa3c-3a91ce380e9c)

**Logs**
If applicable, add logs found in `minecraft-instance/logs/latest.log` and `minecraft-instance/crash-reports/<crashlog>.txt`
no error

**Additional context**

**Comment by DiggityMan420** [comment]
same for TankStorage shall i make another post in tank storage issues exact same thing is here

**Comment by Natanaelel** [comment]
JEI is not supported. Use REI or EMI.
