### ISSUE TITLE
Items are voided when inserted into a docked Bank Link

### ISSUE THREAD

**Issue by StupidUsernameRequirement** [Natanaelel/BankStorage#34]
**Mod version**
1.4.2.+1.21

**Describe the bug**
Items are voided when inserted into a docked Bank Link if the associated Bank has been upgraded and opened without removing the Bank Link from the Bank Dock.

**To Reproduce**
1. Make a Bank and use it to make a Bank Link.
2. Put the Bank Link in a Bank Dock and attach a hopper.
3. Upgrade the Bank.
4. Open the Bank after it is upgraded.
5. Put items into the hopper.

**Expected behavior**
Items in the hopper should be added to the Bank.

**Additional context**
Removing the Bank Link from the Bank Dock and then reinserting it after the bank is upgraded seems to fix the problem.
If the Bank isn't opened after upgrading items will not be voided and will be inserted as expected.

I first encountered the issue in a single-player survival world in the Craftoria modpack. Initially I suspected a mod interaction issues as I was using a Sophisticated Storage barrel with an advanced hopper upgrade but found the issue persisted after changing to a vanilla hopper. I discovered the work-around when I accidentally swapped the Bank Link I had the problem with for a different bank while troubleshooting with a different docked Bank Link with the same problem.

Reproduction was tested in Craftoria v1.8.0 as well as an almost barebones 1.21.1 install using Neoforge 21.1.77 &  EMI 1.1.18+1.21.1+neoforge.

**Comment by Natanaelel** [comment]
Fixed in 1.4.3
