### ISSUE TITLE
Bank Link pickup mode issue

### ISSUE THREAD

**Issue by StupidUsernameRequirement** [Natanaelel/BankStorage#35]
**Mod version**
1.4.2.+1.21

**Describe the bug**
When a Bank Link is made from a Bank that hasn't been opened the initial "No pickup" mode is ignored if the Bank Link is docked without being opened.

**To Reproduce**
1. Make a Bank and then use it to make a Bank Link without opening it.
2. Without opening it put the link in a Bank Dock and use a hopper to insert items.
3. Items are now in the Bank.

**Expected behavior**
Items should remain in the hopper as per the "No pickup" mode setting.

**Additional context**
If the Bank is opened before the Bank Link is made it works as expected.
If the Bank Link is opened before putting it in the Bank Dock it works as expected.
Changing the mode of the docked Bank Link works as expected.

Reproduction was tested in an almost barebones 1.21.1 install using Neoforge 21.1.77 & EMI 1.1.18+1.21.1+neoforge.

**Comment by Natanaelel** [comment]
Fixed in 1.4.3
