### ISSUE TITLE
Allow input and output with chutes and hoppers

### ISSUE THREAD

**Issue by dan55304** [Natanaelel/BankStorage#38]
**Is your feature request related to a problem? Please describe.**
The bank dock doesn't work with chutes and hoppers. I'm looking for a way to have my contraption directly deposit to a linked bank connected to a Tom's mod inventory.

**Describe the solution you'd like**
Input and output via chutes and hoppers.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Natanaelel** [comment]
Make sure the bank has correct settings.

**Comment by dan55304** [comment]
> Make sure the bank has the correct settings.

Yup, that was my problem, thanks so much!
