### ISSUE TITLE
Add Feature: Ability to retain one item when pulling/exporting from a Docked Bank.

### ISSUE THREAD

**Issue by Dogvomit** [Natanaelel/BankStorage#40]
**Is your feature request related to a problem? Please describe.**
I have my main Bank always set to Filtered. I'm always frustrated when automation pulls/exports an item from a docked linked bank and has it take all of that item when auto-crafting or from some other automation. This means I have to re-add the item back into the bank while exploring.

**Describe the solution you'd like**
 - Add an option to always keep one item from a stack.
or 
 - Add an option to lock a slot to an item that will remember to keep picking up that Item when it's empty.

Example:
 - If the slot is locked to say, cobblestone and automation pulls all the cobblestone out of the Bank, 
it will still remember that I want it to keep picking up Cobblestone.
 - if the locked slot is at max capacity it will stop picking up Cobblestone unless you have it set to void overflow.
 - it will not fill up other empty lots if there is a locked slot for that item and it's at max.

![image](https://github.com/user-attachments/assets/0a8629c3-93f4-4896-bf9d-ef928f1fbaf7)

**Comment by Natanaelel** [comment]
Read the description on the mod page. It's already a feature. It works exactly like you described. Hold alt and click any slot to lock it.

**Comment by Dogvomit** [comment]
Well, okay then! I totally missed that. Lol.
