### ISSUE TITLE
Suggestion: Remove Banks from Bank Dock Without Breaking it

### ISSUE THREAD

**Issue by Jaesaces** [Natanaelel/BankStorage#6]
##Suggestion

Allow the player to remove a Bank from its dock without breaking the dock.

As a secondary suggestion, allow the player to right click an occupied dock with another bank to swap them.

**Comment by Natanaelel** [comment]
Shift right click it with an empty hand to remove it.
Swap: Good idea

**Comment by Natanaelel** [comment]
Added in 0.2.0
https://modrinth.com/mod/bank-storage/version/0.2.0

**Comment by Jaesaces** [comment]
I figured out why I couldn't retrieve a bank from its dock before;  if you have a shield in offhand it won't pick up even if your mainhand is empty.  I'm not sure if this is something you can address but I thought it worth bringing up.

**Comment by Natanaelel** [comment]
I'll look into it

**Comment by Natanaelel** [comment]
This can't be fixed without modifying the shield's code, which I don't want to do.
