### ISSUE TITLE
Suggestion: Changing Bank IDs for shared storage

### ISSUE THREAD

**Issue by Jaesaces** [Natanaelel/BankStorage#7]
This feature might be challenging based on you're implementing Banks, but is one of my most used features from Dank Storage.

Basically, in Dank Storage each dank was assigned a sequential ID (I know Bank Storage uses UUIDs instead).  If two danks were the same size, you could manually change the ID of one dank to match another to have them share an inventory.

By doing this, you could effectively use Banks as a sort of Entangled Chest in addition to its other functionality.

**Comment by Natanaelel** [comment]
This is already 90% complete.

**Comment by Jaesaces** [comment]
I saw a commit called "added bank links" but didn't want to get my hopes too high :)

**Comment by Natanaelel** [comment]
Links Added in 0.3.0
https://modrinth.com/mod/bank-storage/version/0.3.0
