### ISSUE TITLE
Suggestion: Mode Display

### ISSUE THREAD

**Issue by Jaesaces** [Natanaelel/BankStorage#8]
Perhaps a minor nitpick, but a display on the bank inventory screen that tells you what mode it's in would be nice.

This is especially relevant for bigger danks where the inventory would cover up the text that appears when you toggle modes.

**Comment by Natanaelel** [comment]
Sure. I might do a textured button with icons

**Comment by Natanaelel** [comment]
Added in 0.3.0
https://modrinth.com/mod/bank-storage/version/0.3.0
