### ISSUE TITLE
Suggestion:  Modes while docked

### ISSUE THREAD

**Issue by Jaesaces** [Natanaelel/BankStorage#9]
Currently I don't think any of the modes do anything when docked, but it could be neat (especially if combined with my suggestion to have the current mode displayed on the bank inventory screen)

1. No Pickup/Pickup All function as normal
2. Filtered Pickup could only accept items already in the Bank
3. Void Excess could function like Filtered Pickup, but also void excess items

**Comment by Natanaelel** [comment]
Good idea, will do.

**Comment by Natanaelel** [comment]
Added in 0.3.0
https://modrinth.com/mod/bank-storage/version/0.2.0
